import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Preview() {
  const [form, setForm] = useState(null);

  useEffect(() => {
    const invoice = JSON.parse(window.sessionStorage.getItem("invoice") ?? "");
    if (invoice) {
      setForm(invoice);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Invoice Preview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container px-16 pt-8 mx-auto">
        <div className="mb-4">
          <Link className="btn" href="/">
            Go back
          </Link>
        </div>
        <section className="grid grid-cols-[3fr_1fr] gap-8">
          <article className="px-8 py-8 mb-20 bg-white border-t-4 border-b-4 border-gray-600">
            <pre>{JSON.stringify(form, null, 2)}</pre>
          </article>
          <aside>
            <button className="btn">Generate PDF</button>
          </aside>
        </section>
      </main>
    </>
  );
}
