import Head from "next/head";
import Link from "next/link";
import { useInvoiceFormContext } from "@/features/invoices/hooks/useInvoiceFormContext";

export default function Preview() {
  const { getValues } = useInvoiceFormContext();
  console.log(getValues());

  return (
    <>
      <Head>
        <title>Invoice Preview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container px-16 pt-8 mx-auto">
        <div className="mb-4">
          <Link className="btn" href="/">
            Go back
          </Link>
        </div>
        <section className="grid grid-cols-[3fr_1fr] gap-8">
          <article className="px-8 py-8 mb-20 bg-white border-t-4 border-b-4 border-gray-600">
            <img
              src={URL.createObjectURL(getValues("logo")?.item?.(0))}
              alt="changemelogo"
              height={100}
              width={100}
            />
            <pre>{JSON.stringify(getValues(), null, 2)}</pre>
          </article>
          <aside>
            <button className="btn">Generate PDF</button>
          </aside>
        </section>
      </main>
    </>
  );
}
